// Parity test: the JS Bayes port (background/bayes.js) must produce the
// same scores as the Go implementation (internal/classify/textbayes) for
// the vectors in bayes_vectors.json (generated by gen_vectors.go).
//
// Run from the repo root or this directory:
//
//	node firefox-extension/test/bayes_parity.mjs

import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import vm from "node:vm";

const here = dirname(fileURLToPath(import.meta.url));
const bg = (f) => readFileSync(join(here, "..", "background", f), "utf8");

// bayes_model.js + bayes.js are classic extension scripts sharing one
// global scope in the background page. Top-level const/class bindings don't
// attach to the vm context object, so evaluate both as a single script and
// capture the bindings from its completion value.
const sandbox = vm.createContext({ console });
const src = `${bg("bayes_model.js")}\n${bg("bayes.js")}\n;({ BayesModel, BAYES_MODEL, classifyText });`;
const exported = vm.runInContext(src, sandbox, { filename: "bayes.js" });

const model = new exported.BayesModel(exported.BAYES_MODEL);
sandbox.classifyText = exported.classifyText;
const vectors = JSON.parse(readFileSync(join(here, "bayes_vectors.json"), "utf8"));

const TOL = 1e-12;
let failures = 0;

for (const v of vectors) {
  const { score, ok } = model.score(v.text);
  if (ok !== v.ok || Math.abs(score - v.score) > TOL) {
    failures++;
    console.error(
      `MISMATCH ${JSON.stringify(v.text.slice(0, 50))}: js={score:${score}, ok:${ok}} go={score:${v.score}, ok:${v.ok}}`
    );
  }
}

// Decision-sequence checks (classifyText mirrors the Go addon's
// HandleResponse): 3 keyword hits block even tiny pages; the 100-char floor
// shields short text from Bayesian scoring noise.
const tiny3Hits = "porn xxx hentai";
if (!sandbox.classifyText(model, tiny3Hits, 0.8).blocked) {
  failures++;
  console.error("MISMATCH: 3 keyword hits on a tiny page must block");
}
const shortAdult = "sexy cams live"; // scores high on Bayes but is <100 chars
const shortVerdict = sandbox.classifyText(model, shortAdult, 0.8);
if (shortVerdict.blocked) {
  failures++;
  console.error("MISMATCH: <100 chars without 3 keyword hits must not block");
}
const longSafe = "The committee reviewed the budget proposal in detail. ".repeat(5);
if (sandbox.classifyText(model, longSafe, 0.8).blocked) {
  failures++;
  console.error("MISMATCH: long safe text must not block");
}

if (failures > 0) {
  console.error(`bayes parity: ${failures} failure(s)`);
  process.exit(1);
}
console.log(`bayes parity: ${vectors.length} vectors + 3 decision checks OK`);
